---
- name: Apply Galaxy Role
  hosts: localhost
  connection: local
  roles:
    - role: indigo-dc.galaxycloud
      create_galaxy_admin: false
      GALAXY_VERSION: "release_19.05"
      create_galaxy_admin: false
      set_pgsql_random_password: false
      set_proftpd_random_password: false
      require_login: 'False' # disable login option only for galaxy images

- name: Post installation tasks
  hosts: localhost
  connection: local
  pre_tasks:
    - set_fact:
        galaxy_user: 'galaxy'

  tasks:
    - name: 'Remove galaxy ssh public key'
      authorized_key:
        user: '{{ galaxy_user }}'
        key: '{{ galaxy_instance_key_pub }}'
        state: absent
    - name: 'Remove root ssh public key' # needed by IM
      authorized_key:
        user: 'root'
        key: '{{ galaxy_instance_key_pub }}'
        state: absent
