---
# Install Galaxy
- name: Apply Galaxy Role
  hosts: localhost
  connection: local
  vars:
    galaxy_version: "<galaxy_version>"
  roles:
    - role: indigo-dc.galaxycloud
      create_galaxy_admin: false
      GALAXY_VERSION: '{{ galaxy_version }}'
      create_galaxy_admin: false
      set_pgsql_random_password: false
      set_proftpd_random_password: false
      require_login: 'False' # disable login option only for galaxy images

# Install tools
- name: Install tools
  hosts: localhost
  connection: local
  vars:
    galaxy_version: "<galaxy_version>"
    galaxy_flavor: "<galaxy_flavor>"
  pre_tasks:
    - name: Set permissions
      file:
        path: '/export'
        state: directory
        owner: 'galaxy'
        group: 'galaxy'
      when: galaxy_flavor != 'galaxy-no-tools'
      become_user: root
      become_method: sudo
  roles:
    - role: indigo-dc.galaxycloud-tools
      galaxy_flavor: '{{ galaxy_flavor }}'
      GALAXY_VERSION: '{{ galaxy_version }}'
      move_datasets: false
      create_bootstrap_user: true
      when: galaxy_flavor != 'galaxy-no-tools'

# Clean image
- name: Post installation tasks
  hosts: localhost
  connection: local
  vars:
    galaxy_user: "galaxy"
    galaxy_instance_key_pub: "<ssh_pub_key>"
  tasks:
    - name: 'Remove galaxy ssh public key'
      authorized_key:
        user: '{{ galaxy_user }}'
        key: '{{ galaxy_instance_key_pub }}'
        state: absent
      ignore_errors: true
    - name: 'Remove root ssh public key' # needed by IM
      authorized_key:
        user: 'root'
        key: '{{ galaxy_instance_key_pub }}'
        state: absent
      ignore_errors: true
